version: "3.9"

services:
    neon-branching-tutorial:
        container_name: neon-branching-tutorial-app
        image: deno
        restart: no
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${DISCORD_BOT_PORT}:${DISCORD_BOT_PORT}"
